# Generated by Django 4.2 on 2026-01-07 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_article_category_alter_article_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='confidence',
            field=models.FloatField(default=0.0),
        ),
    ]
