# Generated by Django 4.2 on 2026-01-08 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_article_confidence'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_reviewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='article',
            name='original_confidence',
            field=models.FloatField(default=0.0),
        ),
    ]
